{% set version = "24.11.1" %}

package:
  name: webcolors
  version: {{ version }}

source:
  fn: webcolors-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/w/webcolors/webcolors-{{ version }}.tar.gz
  sha256: ecb3d768f32202af770477b8b65f318fa4f566c22948673a977b00d589dd80f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - webcolors

about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Library for working with HTML/CSS color formats in Python.

extra:
  recipe-maintainers:
    - jakirkham
